spring:
  application:
    name: inventory-service
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/admin
zeebe:
  client:
    worker:
      defaultName: inventory
    security.plaintext: true
    broker:
      gateway-address: localhost:26500
